### ISSUE TITLE
Exception in thread "main" org.jpmml.evaluator.UnsupportedFeatureException (at or around line 15): RegressionModel

### ISSUE THREAD

**Issue by egbertzeng** [jpmml/jpmml-evaluator-spark#18] opened 2018-01-04 15:31 UTC
can run via idea main  ,but error via  spark-submit .
spark 1.6 ,use branch 1.x
xml:
```
     <DataDictionary numberOfFields="4">
        <DataField name="field_0" optype="continuous" dataType="double"/>
        <DataField name="field_1" optype="continuous" dataType="double"/>
        <DataField name="field_2" optype="continuous" dataType="double"/>
        <DataField name="target" optype="categorical" dataType="string"/>
    </DataDictionary>
    <RegressionModel modelName="linear SVM" functionName="classification" normalizationMethod="none">...
```
error is ：
```
Exception in thread "main" org.jpmml.evaluator.UnsupportedFeatureException (at or around line 15): RegressionModel
        at org.jpmml.evaluator.ModelEvaluatorFactory.newModelEvaluator(ModelEvaluatorFactory.java:126)
        at org.jpmml.evaluator.ModelEvaluatorFactory.newModelEvaluator(ModelEvaluatorFactory.java:66)
        at org.jpmml.evaluator.spark.EvaluatorUtil.createEvaluator(EvaluatorUtil.java:63)
        at org.jpmml.spark.SVMEvaluationSparkExample.main(SVMEvaluationSparkExample.java:50)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by vruusmann** [comment] 2018-01-04 16:19
Duplicate of #7 and #15 - some or all `org.dmg.pmml.*` classes have been incorrectly shaded in your Apache Spark application.

**Closed by vruusmann** 2018-01-04 16:19 UTC
